# Generated by Django 4.2.6 on 2023-10-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='date_livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='date_facturation'),
        ),
        migrations.AlterField(
            model_name='orderhasproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
