# Generated by Django 4.2.6 on 2023-10-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhasproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.product', verbose_name='produit'),
        ),
    ]
