# Generated by Django 5.2.6 on 2026-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_order_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artwork_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='longueur oeuvre'),
        ),
        migrations.AddField(
            model_name='product',
            name='artwork_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='largeur oeuvre'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='cadre'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='marge'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Devis', 'Devis'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Archivée', 'Archivée'), ('Annulée', 'Annulée'), ('Urgent', 'Urgent')], default='En cours', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(max_length=45, verbose_name='descriptif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=45, verbose_name='libellé'),
        ),
    ]
