# Generated by Django 5.2.6 on 2026-02-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_product_artwork_height_product_artwork_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='marge H'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Devis', 'Devis'), ('En cours', 'A faire'), ('Terminée', 'Terminée'), ('Archivée', 'Archivée'), ('Annulée', 'Annulée'), ('Urgent', 'Urgent')], default='En cours', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='marge L'),
        ),
    ]
