# Generated by Django 4.2.6 on 2023-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_orderhasproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
