# Generated by Django 4.2.6 on 2023-10-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_product_purchase_price_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='draw_url',
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='webapp.order')),
            ],
        ),
    ]
