# Generated by Django 4.2.6 on 2023-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_order_draw_url_orderattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderattachment',
            name='url',
        ),
        migrations.AddField(
            model_name='orderattachment',
            name='file',
            field=models.FileField(default='', upload_to='order_attachments/'),
            preserve_default=False,
        ),
    ]
