# Generated by Django 4.2.6 on 2023-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_orderattachment_url_orderattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattachment',
            name='canvas_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
