# Generated by Django 4.2.6 on 2023-10-31 09:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_orderattachment_canvas_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comments',
            field=models.TextField(blank=True, max_length=2000, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='FR', verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=2000, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de facturation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='label',
            field=models.CharField(default='', max_length=45, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(max_length=45, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="prix d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=45, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prix de vente'),
        ),
    ]
