# Generated by Django 4.2.6 on 2023-10-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_customer_address_alter_customer_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente'), ('in progress', 'En cours'), ('done', 'Terminée'), ('invoice', 'Facturée'), ('canceled', 'Annulée')], default='waiting', max_length=32),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
