# Generated by Django 4.2.6 on 2023-11-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_customer_address_alter_customer_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattachment',
            name='type',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
