# Generated by Django 4.2.6 on 2023-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_orderattachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderattachment',
            name='canvas_json',
            field=models.JSONField(null=True),
        ),
    ]
