# Generated by Django 4.2.6 on 2023-11-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_orderattachment_canvas_json'),
        ('webapp', '0013_alter_order_status'),
    ]

    operations = [
    ]
