# Generated by Django 4.2.6 on 2023-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_merge_20231102_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Facturée', 'Facturée'), ('Annulée', 'Annulée'), ('Urgent', 'Urgent')], default='En attente', max_length=32),
        ),
    ]
