# Generated by Django 4.2.7 on 2023-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_customer_first_name_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Réglé', 'Réglé')], default='En attente', max_length=32, verbose_name='Paiment'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Carte bancaire', 'Carte bancaire'), ('Espèce', 'Espèce'), ('Chèque', 'Chèque'), ('Virement', 'Virement')], max_length=32, verbose_name='Type de paiement'),
        ),
    ]
